import { randomUUID } from "node:crypto"
import type { Config, Plugin } from "@opencode-ai/plugin"

/**
 * OpenCode-native equivalent of the request-cleaning part of zen_proxy.py.
 *
 * This plugin runs inside OpenCode's provider fetch path. It deliberately does
 * not start a local HTTP server: OpenCode already owns the HTTP connection and
 * the response/SSE stream. The proxy-only transport features (CONNECT proxy,
 * chunked encoding and SSE keepalive) cannot be controlled from a provider
 * fetch hook and remain the responsibility of the HTTP proxy implementation.
 *
 * It applies to the OFFICIAL "opencode" (Zen) provider: requests routed through
 * it get their session/project/request identity headers rewritten and their
 * body stripped of user/metadata before reaching opencode.ai/zen/v1.
 *
 * Identity rotation is ROUND-BASED, not time-based. OpenCode runs agentically:
 * the user types one message, then the agent keeps executing (many LLM/tool
 * requests) until it stops. All requests belonging to one user message share a
 * single fake identity; a fresh identity is only minted when the user sends the
 * next message (detected via the "chat.message" hook).
 */

// The official OpenCode "opencode" provider (Zen), not a custom provider.
const PROVIDER_ID = "opencode"

const SESSION_HEADERS = [
  "x-opencode-session",
  "x-session-id",
  "x-session-affinity",
  "x-parent-session-id",
] as const
const PROJECT_HEADERS = ["x-opencode-project"] as const
const REQUEST_HEADERS = ["x-opencode-request", "x-opencode-request-id", "x-request-id"] as const

// These headers are hop-by-hop and must not be copied from OpenCode to Zen.
// Host/content-length are also regenerated by fetch for the final request.
const HOP_HEADERS = new Set([
  "host",
  "connection",
  "transfer-encoding",
  "content-length",
  "accept-encoding",
  "expect",
  "keep-alive",
  "proxy-connection",
  "upgrade",
])

function randomID(prefix: string): string {
  return prefix + randomUUID().replaceAll("-", "").slice(0, 22)
}

/**
 * A process-local mapper. Identity is stable for one conversation round and is
 * rotated only when the user sends a new message (see the "chat.message" hook).
 */
class IdentityMapper {
  private readonly sessions = new Map<string, string>()
  private readonly projects = new Map<string, string>()
  private requestID: string | null = null

  /** Start a new round: drop all mappings so the next request gets fresh IDs. */
  rotate() {
    this.sessions.clear()
    this.projects.clear()
    this.requestID = null
  }

  session(realID: string): string {
    if (!realID) return realID
    let fakeID = this.sessions.get(realID)
    if (!fakeID) {
      fakeID = randomID("ses_")
      this.sessions.set(realID, fakeID)
    }
    return fakeID
  }

  project(realID: string): string {
    if (!realID) return realID
    let fakeID = this.projects.get(realID)
    if (!fakeID) {
      fakeID = randomID("proj_")
      this.projects.set(realID, fakeID)
    }
    return fakeID
  }

  request(): string {
    // A single request id shared by every request the agent makes within one
    // round; only changes when the round rotates.
    if (!this.requestID) this.requestID = randomID("req_")
    return this.requestID
  }
}

const identityMapper = new IdentityMapper()

function sanitizeRequestBody(body: Record<string, unknown>): Record<string, unknown> {
  const sanitized = { ...body }
  delete sanitized.user
  delete sanitized.metadata
  return sanitized
}

function sanitizeJSONBody(body: string): string {
  try {
    const parsed: unknown = JSON.parse(body)
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return body
    const object = parsed as Record<string, unknown>
    if (!Object.hasOwn(object, "user") && !Object.hasOwn(object, "metadata")) return body
    return JSON.stringify(sanitizeRequestBody(object))
  } catch {
    // Match zen_proxy.py: non-JSON bodies are forwarded unchanged.
    return body
  }
}

function sanitizeHeaders(headers: Headers): Headers {
  const cleaned = new Headers()

  // Copy all end-to-end headers except hop-by-hop transport headers.
  headers.forEach((value, name) => {
    if (!HOP_HEADERS.has(name.toLowerCase())) cleaned.set(name, value)
  })

  // Use one scope for all session headers, just like the Python mapper. The
  // first available value is the scope key; every present session header gets
  // a stable fake value for the current conversation round.
  const scopeID =
    cleaned.get("x-session-id") ??
    cleaned.get("x-session-affinity") ??
    cleaned.get("x-opencode-session")

  if (scopeID) {
    for (const name of SESSION_HEADERS) {
      const value = cleaned.get(name)
      if (value) cleaned.set(name, identityMapper.session(value))
    }
    for (const name of PROJECT_HEADERS) {
      const value = cleaned.get(name)
      if (value) cleaned.set(name, identityMapper.project(value))
    }
  } else {
    // If there is no usable scope, retain the Python proxy's behavior: only
    // rewrite headers that were actually supplied by the caller.
    for (const name of SESSION_HEADERS) {
      if (cleaned.has(name)) cleaned.set(name, randomID("ses_"))
    }
    for (const name of PROJECT_HEADERS) {
      if (cleaned.has(name)) cleaned.set(name, randomID("proj_"))
    }
  }

  const requestID = identityMapper.request()
  for (const name of REQUEST_HEADERS) {
    if (cleaned.has(name)) cleaned.set(name, requestID)
  }
  if (!cleaned.has("x-opencode-client")) cleaned.set("x-opencode-client", "cli")

  return cleaned
}

function createSanitizingFetch(): typeof fetch {
  return (async (
    input: Parameters<typeof fetch>[0],
    init?: Parameters<typeof fetch>[1],
  ) => {
    const inputRequest = input instanceof Request ? input : null
    const headers = new Headers(inputRequest?.headers)
    if (init?.headers) {
      new Headers(init.headers).forEach((value, name) => headers.set(name, value))
    }

    let body = init?.body
    if (body === undefined && inputRequest && inputRequest.method !== "GET" && inputRequest.method !== "HEAD") {
      // clone() avoids consuming the Request that the provider may still use.
      body = await inputRequest.clone().text()
    }

    if (typeof body === "string") {
      const sanitized = sanitizeJSONBody(body)
      if (sanitized !== body) headers.delete("content-length")
      body = sanitized
    }

    const finalHeaders = sanitizeHeaders(headers)
    return fetch(input, {
      ...init,
      headers: finalHeaders,
      ...(body === undefined ? {} : { body }),
    })
  }) as typeof fetch
}

function configureZenProvider(config: Config, cleanFetch: typeof fetch) {
  // The official "opencode" (Zen) provider is built-in; it may not be present
  // in config.provider unless the user overrode it. Create/merge the entry so
  // our sanitizing fetch applies to the official channel as well.
  config.provider ??= {}
  const provider = (config.provider[PROVIDER_ID] ??= {})

  provider.options ??= {}
  // baseURL is intentionally left untouched: the official provider already
  // defaults to https://opencode.ai/zen/v1 and the user may have overridden it.
  provider.options.fetch = cleanFetch
  provider.options.transformRequestBody = sanitizeRequestBody
  // Long reasoning/SSE responses must not be cut off by a client timeout.
  provider.options.timeout = false
}

export default (async () => {
  const cleanFetch = createSanitizingFetch()
  let lastUserMessageID: string | null = null

  return {
    config: async (config) => {
      configureZenProvider(config, cleanFetch)
    },

    "chat.message": async (input) => {
      // A new user message starts a new round: rotate the fake identity once.
      // Dedupe by messageID so re-fires of the same message don't rotate again
      // in the middle of the agent's continuous execution.
      if (input.messageID && input.messageID === lastUserMessageID) return
      lastUserMessageID = input.messageID ?? null
      identityMapper.rotate()
    },

    "chat.headers": async (input, output) => {
      if (input.model.providerID !== PROVIDER_ID) return

      // Pass the real OpenCode session into cleanFetch. cleanFetch performs the
      // actual stable mapping, so the ID is not randomly rewritten twice.
      const sessionID = input.sessionID || randomID("ses_")
      output.headers["x-session-id"] = sessionID
      output.headers["x-session-affinity"] = sessionID
      if (!output.headers["x-opencode-client"]) {
        output.headers["x-opencode-client"] = "cli"
      }
    },
  }
}) satisfies Plugin
